# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b526f17aa1007652bcd40f76698542e42e3eec059c7d98cf7946a4ebf2db9eb8d9a77fb75fbe86947f5e3d485450c03f8c828e2828e4b41f69fb1a02e2cf78b

test:
  secret_key_base: 7c7c525917c17c507a2710bb02190a4a837830d49767071ddb3618ac6066a4ccf33d7faae2d7e92d961ad292d89f80b724ab1ebd16b5963add4dda6e0585b7ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
